CreateRule/urls.py
from django.conf.urls import url
from CreateRule import views
# SET THE NAMESPACE!
app_name = 'CreateRule'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^create_rule/$', views.create_rule, name='create_rule'),
    url(r'^see_rules/$', views.see_rules, name='see_rules'),
    url(r'^upload_file/$', views.upload_file, name='upload_file'),
    url(r'^edit/$', views.edit, name='edit'),
]

engine/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from CreateRule import views
urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^CreateRule/',include('CreateRule.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

CreateRule/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
      return self.user.username

class Images(models.Model):
    image = models.ImageField(upload_to='plot', blank=True)

CreateRule/forms.py
from django import forms
from CreateRule.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site', 'profile_pic')

CreateRule/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from matplotlib import image
import ast, json
import pandas as pd
from django.conf import settings
from django.shortcuts import render
from CreateRule.forms import UserForm, UserProfileInfoForm
from CreateRule.engine import *
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from CreateRule.charts import *

def index(request):
    return render(request, 'CreateRule/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'CreateRule/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'CreateRule/login.html', {})


def create_rule(request, code=''):
    if request.method == 'POST':
        # if the request made is to save the code then
        if request.POST.get('save'):
            code = request.POST.get('code')
            out = save_code(code)
            print('saving..')
            return render(request, 'CreateRule/create.html', {'validated': 'True',
                                                              'code': code,
                                                              'output': out,
                                                              'saved': 'True'})
        # if the request made is for sending the inp since code has been verified then execute the input
        if request.POST.get('column'):
            inp = dict()
            column = request.POST.getlist('column')
            type = request.POST.getlist('type')
            code = request.POST.get('code')
            for item, value in zip(column, type):
                inp[item.encode('ascii', 'ignore')] = value.encode('ascii', 'ignore')
            output = evaluate(code, inp)
            return render(request, 'CreateRule/create.html', {'validated': 'True',
                                                                  'code': code,
                                                                  'output': output,
                                                              'input': inp })

        elif request.POST.get('code'):
            code = request.POST.get('code')
            print(code)
            if validate(code):
                out = 'validated'
                return render(request, 'CreateRule/create.html', {'code': code,
                                                                  'validated': 'True'})
            else:
                print(validate(code))
                return render(request, 'CreateRule/create.html', {'code': code,
                                                                  'out': 'false',
                                                                  'validated': 'try_again'})
    else:
        return render(request, 'CreateRule/create.html', {'out': '',
                                                          'validated': 'False',
                                                          'code': code})

def see_rules(request):
    if request.method == 'POST':
        cell = request.POST.get('code')
        print(cell)
        delete_row(cell)
        out = show()
        code = out['code']
        return render(request, 'CreateRule/show.html', {'rule': out['rule'],
                                                        'code': code,
                                                        })
    else:
        out = show()
        code = out['code']
        return render(request, 'CreateRule/show.html', {'rule': out['rule'],
                                                        'code': code,
                                                        })
def upload_file(request):
    if request.method == 'POST' and request.FILES['file']:
        # get the file
        file = request.FILES['file']

        # convert file to csv
        df = pd.read_csv(file)

        # clean the df
        df = clean(df)

        # create dictionary of attributes from df
        dict_file = get_attributes(df)

        # get the output for the passed rules
        output = execute_all(dict_file)

        # convert the output dictionary to a new dict for ease in django template
        # output is a dict having values like {'chart_type':'plot'}
        temp = {}
        url = {}
        for i, d in enumerate(output):
            temp[i] = d
            # print(d)
            url[i] = chart(df, output=d )

        # get all the codes from dictionary
        out = show()
        code = out['code']
        # img = image.imread(settings.MEDIA_ROOT + '/plot/6.png')
        # print(dir(img))
        # img.view()
        return render(request, 'CreateRule/upload.html', {'uploaded': 'True',
                                                          'dict': dict_file,
                                                          'output': temp,
                                                          'code': code,
                                                          'plots': url, })
    else:
        return render(request, 'CreateRule/upload.html', {})

def edit(request):
    if request.method == 'POST':
        pass
    return render(request, 'CreateRule/create.html', {})

templates/CreateRule/Rule.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
      <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'CreateRule/style.css' %}" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <style>
          *,
        *::before,
        *::after{

            box-sizing: border-box;

        }

        *:focus{
            outline: none;
        }

        body{

            padding: 0;
            margin: 0;
            background: #000;
            color: white;
            font-family: "oxygen", sans-sarif;

        }
        .jumbo{
            background: #060606;
            color: white;
            font-family: "oxygen", sans-sarif;
            border: 2px solid white;

        }




      </style>

</head>
  <body class="body">
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Create Rules </a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'CreateRule:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'CreateRule:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/CreateRule/create.html
{% extends "CreateRule/Rule.html" %}
{% block body_block %}
<style>
    * {
    font-size : 15px;
    letter-spacing : 1px;
    }

    .code{
            padding: 5px;
            background: #17141d;
            color: #c2c2c2;
            width: 50%;
            float: left;
            border: 1px solid white;
            height: 400px;
            resize: vertical;
        }

        .input{
            padding: 5px;
            background: #17141d;
            width: 50%;
            height: 400px;
            float: right;
            border: 1px solid white;
            resize: vertical;
        }


        .result{
            padding: 5px;
            background: #17141d;
            width: 100%;
            height: 200px;
            position: relative;
            border: 1px solid white;
            resize: vertical;
        }
        .code:hover, .result:hover, .input:hover{
        border: 2px solid white;
        }
        .footer{
        color: gray;
       text-align: center;
       bottom: 0px;
       width: 100%;
   }

   #save{
       background-color:#000;
       padding: 5px 20px 5px 20px;
       border: none;
       margin: 3px;
       font-size : 15px;
       letter-spacing : 1px;
   }
   #save:hover{
        border: 1px solid white;
   }
   .column{
   width:45%;
   background-color:#000;
   color:white;
   color: #20C20E;
   font-size:20px
   }
</style>
<section>
    <div class="container">


        <div class="code">
            <nav class="navbar navbar-inverse" >
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="">Start Coding..</a></li>
                    <li><a class="nav-link " href="{% url 'CreateRule:create_rule' %}">Refresh</a></li>

<!--                    To save the code-->
                    {% if validated == 'True' %}
                    <form class=" nav navbar-form navbar-right" method="post" enctype="multipart/form-data" >
                        <div class="form-group">
                            {% csrf_token %}
                            <textarea type="text" hidden name="code">{{ code }}</textarea>
                            <li><button id = 'save' type="submit" name="save" value="save">Save</button> </li>
                        </div>
                    </form>
                    {% endif %}
                </ul>
            </nav>
            {% if validated == 'try_again' %}
            <div style="color:red">
                Invalid Code
            </div>
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    {% csrf_token %}
                    {% if validated == 'False' or validated == 'try_again' %}
                        <textarea name="code" required class="form-control" rows="9" style="background-color: #000; color: #20C20E; font-size:20px">{{code }}</textarea>
                        <div class="text-right">
                            <button type="submit" class="btn btn-success" name="" style="margin:5px">Validate</button>
                        </div>
                    {% else %}
<!--                    show the code if validated-->
                    <div class="" style="background-color: #000; color: #20C20E;">
                        {{ code|linebreaks }}
                    </div>
                    <div class="footer">
                        {% if saved == 'True' %}
                        Code saved successfully
                        {% else %}
                        Code Validated successfully
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
            </form>

    </div>

<!--        input class-->
        <form method="post" enctype="multipart/form-data" class="form">
            {% if validated == 'True' %}
                {% csrf_token %}
        <div class="input" style="overflow-y:auto">
            <nav class="navbar navbar-inverse" >
                <ul class="nav navbar-nav">
                  <li><a class="navbar-brand" href="">Input.. </a></li>
                    <li>
                        <input class="btn" type="button" id="add" value = "Add Column" style="margin:10px; background-color: #000; border:none; color: white">
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <button type="submit" class="btn btn-success" name="" style="margin:10px 30px 10px 10px"> RUN </button>
                </ul>
            </nav>

                <textarea hidden name="code">{{ code }}</textarea>
                <table>
                    <tbody id="columns">

                    {% for key, value in input.items %}
                    <div style="display:block">
                        <input type="text" placeholder="Column name*" name="column" maxlength="100" class="form-control column" style="float:left" required value="{{ key }}">
                        <select name="type" class="form-control column " style="float:right">
                        {% if value  == 'metrics' %}
                            <option value="metrics" selected>Metrics</option>
                            <option value="categorical">Categorical</option>
                            <option value="temporal_dimension">Temporal</option>
                        {% elif value == 'categorical'  %}
                            <option value="metrics" >Metrics</option>
                            <option value="categorical" selected>Categorical</option>
                            <option value="temporal_dimension">Temporal</option>
                        {% else %}
                            <option value="metrics" selected>Metrics</option>
                            <option value="categorical">Categorical</option>
                            <option value="temporal_dimension" selected>Temporal</option>
                        {% endif %}
                        </select>
                        <br><br>
                    </div>
                    {% endfor %}

                    </tbody>
                </table>
            {% endif %}
        </div>
        </form>
    </div>
</section>
<section>
    {% if validated == 'True' %}
    <div class="container">
        <div class="result">
            <h2 align="center"> Result </h2>
            <div style="color: blue; font-size: 20px">
<!--                {{ output }}-->
                {% for key, value in output.items %}
                {{key}} - {{value}}<br>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</section><br><br><br>
<script>
      var id = 0;
      var clas = "";

      $(document).ready(function(){
      $('#add').click(function(){
            var html = [];


            html.push('<div class="attrib_'+id+'"><input type="text" placeholder="Column name*" name="column" maxlength="100" class="form-control column" style="float:left" required><button class="text-right" type="button" id="attrib_'+id+'" style="background-color:red; border:none; display:inline; margin-left:10px ">-</button><select name="type" class="form-control column " style="float:right"><option hidden></option><option value="metrics">Metrics</option><option value="categorical">Categorical</option><option value="temporal_dimension">Temporal</option></select><div class="attrib_'+id+'" style="float:right"><br><br></div><br><br></div>');

            $('#columns').append(html);
            id+=1

            $('button').click(function(){
            var cla = "";
            cla = "."+$(this).attr("id");
            $('div').remove(cla);
            });
            });

      $('#remove').click(function(){
      if(id>0){
            clas = ".attrib_" + (id-1);
            $('div').remove(clas);
            id-=1;
            }
            });


            $("p").css({"font-size": "20px"});

            });

</script>
<script>
    console.log(newURL)
</script>

{% endblock %}

templates/CreateRule/index.html
{% extends "CreateRule/Rule.html" %}
{% block body_block %}
<div class="container ">
  <div class="jumbotron jumbo">
    <h1>Welcome to the Ruled Engine !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <h3> <a href="">Create Rule</a> </h3>
    {% else %}
        <h2>Register or Login if you'd like to create Rules</h2>
      <h3><a href="{% url 'CreateRule:create_rule' %}"> Create Rule</a> </h3>
      <h3><a href="{% url 'CreateRule:see_rules' %}">See Rules</a> </h3>
      <h3><a href="{% url 'CreateRule:upload_file' %}">Testing</a></h3>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/CreateRule/login.html
{% extends 'CreateRule/Rule.html' %}
{% block body_block %}
<style>
    * {
    font-size : 20px;
    letter-spacing : 2px;
    }
</style>
  <div class="container">
    <div class="jumbotron jumbo">
      <h1 align="center">Login</h1><br><br>
    <form method="post" action="{% url 'CreateRule:user_login' %}" >
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username" class="form-control">

            <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password" class="form-control">
        </div>
    <input type="submit" name="" value="Login" class="btn btn-success btn-lg btn-block">
</form>
</div>
  </div>
{% endblock %}

templates/CreateRule/registration.html
{% extends "CreateRule/Rule.html" %}
{% load static %}
{% block body_block %}
<style>
    * {
    font-size : 20px;
    letter-spacing : 2px;
    }
    .note
{
    text-align: center;
    height: 80px;
    background: -webkit-linear-gradient(left, #0072ff, #8811c5);
    color: #fff;
    font-weight: bold;
    line-height: 80px;
}
.form-content
{
    padding: 5%;
    border: 1px solid #ced4da;
    margin-bottom: 2%;
}
.form-control{
    border-radius:1.5rem;
}
.btnSubmit
{
    border:none;
    border-radius:1.5rem;
    padding: 1%;
    width: 20%;
    cursor: pointer;
    background: #0062cc;
    color: #fff;
}
</style>
  <div class="container">
    <div class="jumbotron jumbo">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
<!--        <h3 align="center"> Fill out the form to execute rules</h3>-->
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
    <div class="container register-form">
            <div class="form">
                <div class="note">
                    <p>Register Yourself</p>
                </div>

                <div class="form-content">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Username *" name="username" required id="id_username" maxlength="150" />
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Password *" name="password" required id="id_password"/>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="form-control" placeholder="Portfolio site *" type="url" name="portfolio_site" id="id_portfolio_site" maxlength="200" />
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Profile Pic" type="file" name="profile_pic" id="id_profile_pic"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="email" name="email" placeholder="Email *" id="id_email" maxlength="254" />
                        </div>
                    </div>
                    <button type="submit" class="btnSubmit text-right" value="">Submit</button>
                </div>
            </div>
        </div>


</form>
      {% endif %}

    </div>
  </div>


{% endblock %}

templates/CreateRule/show.html
{% extends "CreateRule/Rule.html" %}
{% block body_block %}
<style>
    .on_top{
    z-index:1000;
    position: fixed;
    background-color:blue;
    color:white;
    width: 30%;
    height: 20%;
    align: center;
    margin-top: 200px;
    margin-left: 300px;
    padding-top: 30px;
    padding-left: 30px;
    }

    .blur{
    filter: blur(3px)
    }

    .btn{
    margin:10px;
    }

</style>
<div class="on_top" id="" hidden >
    Please confirm if you want to delete the Rule
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input hidden type="text"  value="input" name="code">
        <input type="submit" value=" Confirm " class="confirm btn btn-danger">
        <input type="button" value=" Cancel " class="cancel btn btn-success">
    </form>
</div>

<div class="table-responsive-md">
<table class="table table-dark">
    <thead >
    <tr>
        <th scope="col">
            Rule no.
        </th>
        <th scope="col">
            Rule
        </th>
    </tr>
    </thead>
    <tbody>
    {% for key, value in code.items %}
    <tr id= {{key}} >
        <th scope="row">
            {{ key }}
        </th>
        <td>
            {{ value|linebreaks }}
        </td>
        <td>
            <button class="delete btn btn-primary">
                Delete
            </button>
             <button class="edit btn btn-primary">
                Edit
            </button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>

<!--Below script is for the delete button on the page-->
<script>
    $(document).ready(function(){
      $('.delete').click(function(){
      $(this).closest('table').attr('class', 'blur');
      $('.on_top').removeAttr('hidden');
      $(this).closest('tr').attr('hidden','');
      var id = $(this).closest('tr').attr('id');


          $('.confirm').click(function(e){
            $('input[type="text"]').val(id);
          });

          $('.cancel').click(function(e){
            location.reload(true);
          });

      });
      setTimeout(function(){
      $('#request').fadeOut();}, 200);

    });
</script>
<script>
        $(document).ready(function(){
      $('.edit').click(function(){
<!--            in case this button wont work out on deployment use this below code-->
<!--            var newURL = window.location.protocol + "//" + window.location.host-->
            var newURL =  window.location.protocol + "//" +window.location.host + "/CreateRule/create_rule/";
            window.location.href = newURL;

      });

      });
</script>
{% endblock %}
<!--      -->

templates/CreateRule/upload.html
{% extends "CreateRule/Rule.html" %}
{% block body_block %}
<style>
    input[type='file']{
    width:100%;
    background-color:red;
    }
</style>
{% if uploaded != 'True' %}
<form class="form" method="post" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}

        <center>
            <input type="file" name="file" class="form-control" accept=".csv" style="width: 40%; height: 100px; margin:20px; align:center; padding: 30px">
            <input type="submit" class="btn btn-success" name="submit" value="Submit">
        </center>

    </div>
</form>
{% elif uploaded == 'True' %}

<div  style="background-color:gray; color:black; padding:10px; margin:30px; height: 150px; border: 2px solid red; overflow-y:auto">
    <div style="background-color:yellow" id="upload"> file uploaded successfully </div>
    <br>
    <div align="center"> Predicted columns </div>
    {% for key, value in dict.items %}
    {{key}} -> {{value}}
    <br>
    {% endfor %}
</div>

<div class="table-responsive-md">
<table class="table table-dark">
    <thead >
    <tr>
        <th scope="col">
            Rule no.
        </th>
        <th scope="col">
            Rule
        </th>
        <th scope="col">
            Output
        </th>
        <th scope="col">
            PLOT
        </th>
    </tr>
    </thead>
    <tbody>
    {% for key, value in code.items %}
    <tr id= {{key}} >
        <th scope="row">
            {{ key }}
        </th>
        <td>
            {{ value|linebreaks }}
        </td>
        <td>
            {% for k,v in output.items %}
                {% if k == key %}
                    {% for key, value in v.items %}
                        {{key}} -> {{value}}
                        <br>
                    {% endfor %}
                {% endif %}

            {% endfor %}
        </td>
        <td>
            {% for ke ,plot in plots.items %}
                {% if ke == key %}
                    <img src="data:image/png;base64,{{ plot }}" alt="" height="200" ,width="200">
                {% endif %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>
<script>
    $('#upload').delay(5000).fadeOut(400)
</script>

{% endif %}
{% endblock %}